name: EPG Generator Secure
on:
  schedule:
    - cron: "0 */1 * * *"  # Cada 1 horas
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Evita ejecuciones infinitas
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install requests beautifulsoup4 lxml
          
      - name: Run Secure EPG Generator
        run: python epg_generator.py
        
      - name: Commit and Push
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add twitch_epg.xml images/
          git commit -m "🛡️ EPG seguro actualizado"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
