name: Update Twitch IPTV List
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    timeout-minutes: 5  # Evita ejecuciones infinitas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install yt-dlp
          sudo apt-get install -y ffmpeg coreutils
          
      - name: Run updater script
        run: |
          chmod +x twitch_iptv_updater.sh
          ./twitch_iptv_updater.sh
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add twitch_iptv.m3u
          git commit -m "Auto-update IPTV list"
          git push origin HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
